server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jnugDave/spring-cloud-config

#          uri: file://C:\git-local-repo
